### ISSUE TITLE
Document a Nested XML to Model and vice versa

### ISSUE THREAD

**Issue by kavink** [geirolz/advxml#131]
Would be really nice to have an Example where a nested XML is converted to model and vice versa. Reading the docs it seems simple to convert a simple XML to model.

e.g. how to convert nested XML example from docs to model ?

```
case class Person(name: String, surname: String, age: Option[Int], cars: Seq[Car], pronouns: Option[Seq[String]])
case class Car(brand: String, price: String)
```

**Comment by geirolz** [comment]
Hi @kavink , thanks for reporting!
Anyway you can check  [XmlConverterSyntaxTest](https://github.com/geirolz/advxml/blob/master/src/test/scala/advxml/syntax/XmlConverterSyntaxTest.scala) to see a simple example. 

Unfortunately there is no auto derivation for now, i hope to introduce it in the future.

Let me know if it still not clear :) 

P.S. I'm working on huge refactoring abount this part., i hope to release it next month. If you want you can check `develop` branch to see some news.

**Comment by geirolz** [comment]
@kavink v2.3.0-RC1 is out now! 
I'm working on the documentation for this release. 
If you want check it, i hope now it's more easy to use
