### ISSUE TITLE
Transformer engine apply transformation only on the first NodeSeq that match the XmlZoom

### ISSUE THREAD

**Issue by geirolz** [geirolz/advxml#139]
`XmlRule` transform engine doesn't work as expected when there are multiple `NodeSeq` that match `XmlZoom` actions. 
The transformation is applied only on the firt `NodeSeq` that match.

```scala

val doc = <foo>
    <bar />
    <bar />
    <bar />
</foo>

val result : NodeSeq = doc.transform[Try](root.bar ==> SetAttrs(k"T" := 10)).get()

/*
* Expected
* <foo>
*    <bar T="10" />
*    <bar T="10" />
*    <bar T="10" />
* </foo>
*
* Actual
* <foo>
*    <bar T="10" />
*    <bar />
*    <bar />
* </foo>
*/
```

**Comment by geirolz** [comment]
> @geirolz The issue #139 is already fixed ??

@pawelkaczor sorry for the delay, I didn't see your comment about this but until today. 
No, the bug is still open, if you have any suggestions you are welcome. 

Currently, this remains the only known bug unresolved for this library.

**Comment by geirolz** [comment]
Checking current implementation in `XmlRule.buildRewriteRule` this is more complex than it appears. At the first look, I think that we have to completely re-think the logic on the `XmlModifier` application.

**Comment by pawelkaczor** [comment]
> > @geirolz The issue #139 is already fixed ??
> 
> @pawelkaczor sorry for the delay, I didn't see your comment about this bug until today.
> No, the bug is still open, if you have any suggestions you are welcome.
> 
> Currently, this remains the only known bug unresolved for this library.

@geirolz But the test that I added does say opposite, the bug seems to be resolved. Do you have a (failing) test that confirms the issue?

**Comment by geirolz** [comment]
I'm sure that the example reported in this issue was failing. I didn't change the logic in the meanwhile so this is quite strange, let me check.

**Comment by geirolz** [comment]
Just checked, idk why but it works now.
