### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by geirolz** [geirolz/advxml#30]
AS: Users
IW: Have more documentation about Advxml features with examples
SO: We can create more markdown files, one for each feature.

Features:
- [ ] Xml Transformer
- [ ] Xml Traverser
- [ ] Xml Converter
- [ ] Xml Normalizer

**Comment by erickneverson** [comment]
Is this backwards compatible with previous versions of Scala?  It's not quite clear in the documentation and I'm using 2.11.12 currently.

**Comment by geirolz** [comment]
> Is this backwards compatible with previous versions of Scala? It's not quite clear in the documentation and I'm using 2.11.12 currently.

Hi @erickneverson, yes this library works also with 2.11.X
