### ISSUE TITLE
Cannot resolve symbol syntax

### ISSUE THREAD

**Issue by erickneverson** [geirolz/advxml#45]
v0.1.6
`import com.github.geirolz.advxml`
`//Advxml imports`
`import advxml.transform.XmlRule`
`//Supply $ and ==> syntax`
`import advxml.syntax.transform._`
`//Supply Append class`
`import advxml.instances.transform._`

compiler throws error for line `advxml.syntax.transform._` **cannot resolve symbol syntax**.

Also the first import is not documented but is required in order for the subsequent lines to compile.

**Comment by geirolz** [comment]
Hi @erickneverson, what you see in the [documentation](https://geirolz.github.io/advxml/) is for the incoming release **v2.0.0**, i suggest you to use the **v2.0.0-RC1**. 
Let me know if you still have this problem

**Comment by erickneverson** [comment]
**v2.0.0-RC1** works, thank you.
