### ISSUE TITLE
Transform existing XML

### ISSUE THREAD

**Issue by erickneverson** [geirolz/advxml#46]
With the following structure
`<SomeFields>`
`<ABC>111</ABC>`
`</SomeFields>`

SomeFields is my root node. 

1. What rule allows me to add a child node to SomeFields
e.g.
`<SomeFields>`
`<ABC>111</ABC>`
`<DEF>222</DEF>`
`</SomeFields>`

2. What rule allows me to edit a child node
`<SomeFields>`
`<ABC>444</ABC>`
`<DEF>222</DEF>`
`</SomeFields>`

This would be useful info for your documentation.  Thanks in advance!

**Comment by erickneverson** [comment]
I was able to figure out how to add a node to my XML

`val doc: Elem = XML.loadString(s"<$fieldName>$fieldValue</$fieldName>")`
`val result: Try[NodeSeq] = xml.transform[Try](Append(doc))`

Now, I just need to know how to update the value of an existing node.

**Comment by geirolz** [comment]
What do you mean with " I just need to know how to update the value of an existing node." ? 

P.S. For root transformation i'm doing some changes, i'll introduce "root" value and you can use it statically.

```scala
val doc : Elem = XML.loadString(s"<$fieldName>$fieldValue</$fieldName>")
val result: Try[NodeSeq] = xml.transform[Try](root ==> Append(doc))
```

This change allows modifiers combination and a more readable code.
Check release 2.0.0 in the next weeks.

**Comment by geirolz** [comment]
Thanks for your help @erickneverson. Please in the future put some labels on your issues so i can understand better your requests 👍

**Comment by erickneverson** [comment]
For example:

xml: Elem
contains the following XML
`<SomeFields>`
`<ABC>444</ABC>`
`</SomeFields>`
I need to change the value of 444 to 555 in the ABC node.

**Comment by erickneverson** [comment]
I figured it out.  I was referencing the current node incorrectly. Here is the end result:

`val currentNode = (xml \\ fieldName)`
      `val newNode: NodeSeq =`
        `XML.loadString(s"<$fieldName>$fieldValue</$fieldName>")`
     ` val rule = $(Function.const(currentNode)) ==> Replace(_ => newNode)`
      `val result: NodeSeq = xml.transform[Try](rule).get`

fieldName is a String which = ABC in the example above.

**Comment by erickneverson** [comment]
@geirolz I made a new discovery which hopefully you can reproduce or guide. Based on the sample XML and code below:

<SomeFields>
<ABC>444</ABC>
</SomeFields>

xml: Elem

val currentNode = (xml \\ "ABC")
val newNode: NodeSeq =
XML.loadString("<ABC>444</ABC>")
val rule = $(Function.const(currentNode)) ==> Replace(_ => newNode)
val result: NodeSeq = xml.transform[Try](rule).get

Because I'm replacing the node with the same value, the full XML is never returned. Instead, <ABC>444</ABC> is returned. If the value 444 is something different, the whole XML be returned as expected.

**Comment by geirolz** [comment]
Ok this is a bug. Thanks for your test.
I'll fix this in the next release.

```scala
import advxml.instances.transform._
import advxml.syntax.transform._
import cats.instances.try_._

import scala.util.Try
import scala.xml.NodeSeq

val xml = <A><B>1</B></A>

val rule = $(_ \ "B") ==> Replace(_ => <B>1</B>)
val result: NodeSeq = xml.transform[Try](rule).get
//expected <A><B>1</B></A>
//got <B>1</B>
```

**Comment by geirolz** [comment]
Hi @erickneverson, please check lastest release v2.0.0-RC3.

**Comment by erickneverson** [comment]
This line now fails:

      `val result: Try[NodeSeq] = xml.transform[Try](Append(doc))`

```
Error:(142, 47) overloaded method value transform with alternatives:
  (f: Seq[scala.xml.transform.RewriteRule] => scala.xml.transform.BasicTransformer)(rules: advxml.core.transform.XmlRule*)(implicit evidence$2: advxml.core.validate.MonadEx[scala.util.Try])scala.util.Try[scala.xml.NodeSeq] <and>
  (rule: advxml.core.transform.XmlRule,rules: advxml.core.transform.XmlRule*)(implicit evidence$1: advxml.core.validate.MonadEx[scala.util.Try])scala.util.Try[scala.xml.NodeSeq]
 cannot be applied to (advxml.implicits.Append)
      val result: Try[NodeSeq] = xml.transform[Try](Append(doc))
```
What changes do I need to make?

**Comment by geirolz** [comment]
@erickneverson please check the documentation about root transformation

**Comment by geirolz** [comment]
@erickneverson any update ?

**Comment by erickneverson** [comment]
@geirolz sry I got slammed the past few days.  I'll update some time tomorrow.

**Comment by erickneverson** [comment]
@geirolz I'm still facing the same issue:
Cannot resolve symbol transform.  The problem is most likely on my end somehow so I'll keep looking.  Just wanted to get back to you like I said I would.
