### ISSUE TITLE
XPath support

### ISSUE THREAD

**Issue by geirolz** [geirolz/advxml#57]
AS: User
IW: Convert XPath string into `XmlZoom` instance
So: We provides a method into `XmlZoom` to create an `XmlZoom` instance given the XPath string.

The methods will have the following signature: 
```scala
def fromXPath(value: String) : F[XmlZoom]
```
The methods will be placed into `XmlZoom` companion's object.

**Comment by danslapman** [comment]
Hello! Can't find `fromXPath` in companion object (v2.5.0), was this feature implemented?

**Comment by geirolz** [comment]
> Hello! Can't find `fromXPath` in companion object (v2.5.0), was this feature implemented?

Hi @danslapman! Unfortunately I did implemented this feature yet. 
I'm working on a new project _cats-xml_ and I'm planning to add this feature there. 

Since the xpath parser is just based on _String_ I can try to port this feature in _Advxml_ as well. 

I'm gonna to reopen this issue in order to keep track of this work.

**Comment by danslapman** [comment]
Hi @geirolz! Thanks for clarification. I already investigated advxml's source and I want to work on XPath support by myself in near. I'm planning to implement xpath parser via fastparse and then build XmlZoom from parsed AST. I would love to contribute my work in advxml if You're interested

**Comment by geirolz** [comment]
`fastparse` could be iteresting. In Scala 2.13 there is the possibility to deconstruct Strings in pattern matching, this could be useful if you thing about the xpath as a tail-recoursive application like a foldLeft where the zero is the Root. 
Xpath shouldn't be to much complex to implement with this approach maybe. 

Anyway, any contribution is welcome! So yes, please, if you know how to implement this and you want to help this project you are more than welcome! ☺️

I've never used `fasrparse`, looks interesting and maybe it's sampler and performs bettern that string decomposition 
If you have experience with `fasrparse`, this is totally fine to do this with that library

**Comment by danslapman** [comment]
XPath have complex grammar, parsing it with de-interpolation will be extremely tricky (from my point of view). Anyway, I found, that `fastparse` currently doen't have 3.x artifact, so possible candidated (for parser) now are parboiled2 and atto (which is easier, but slower). Any way, I'll try to write a parse using publicly-awailable grammar in a week or two

**Comment by danslapman** [comment]
Suddenly found a cat-parse-based parser https://github.com/dvreeze/xpathparser, will try it out for prototyping

**Comment by geirolz** [comment]
> sed parser https://github.com/dvreeze/xpathparser, will try it out for prototyping

This looks very very interesting to me, I agree that deconstructing strings and manually pattern matching is too hard given the xpath syntax. Thank you very much for this suggestion!

**Comment by danslapman** [comment]
I'm already working on this :) You may assign me on this issue

**Comment by danslapman** [comment]
@geirolz please, take a look at #317, it's a minimal WIP, if this design is okay in general, I will continue my work

**Comment by danslapman** [comment]
Thank You 🎉
